sonar.projectKey=insy7314-backend
sonar.projectName=insy7314-backend
sonar.sourceEncoding=UTF-8
sonar.sources=src
sonar.tests=test
sonar.javascript.lcov.reportPaths=coverage/lcov.info
sonar.exclusions=src/index.js,src/seed/**,src/**/__mocks__/**  # exclude bootstrap & non-code
